# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    ignore:
      # Ignore all major updates
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      angular:
        patterns:
          - "@angular/*"
          - "@angular-eslint/*"
      ng-icons:
        patterns:
          - "@ng-icons/*"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # Ignore all major updates
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "actions/*"
      docker:
        patterns:
          - "docker/*"
